### ISSUE TITLE
Can't open file for reading on MacOS

### ISSUE THREAD

**Issue by matthieu-lapeyre** [RobotsWar/Plater#36]
Hi 

I did not managed to make Plater work. I always have the can't open file error:
<img width="551" alt="capture d ecran 2015-11-27 a 08 02 54" src="https://cloud.githubusercontent.com/assets/4503773/11435670/4f8f9e38-94dd-11e5-8eba-8695bd7e4546.png">

I tried to remove all whitespaces in the file path but it does not fix the problem.

Any idea ?

Thanks

**Comment by Gregwar** [comment]
Hello Matthieu!
Actually, I'm pretty sure your problem is the `file://` prefix. Qt is used as a gui, but the backend function for actually read the file is C++ stream (Plater CLI does not depend on Qt) which I think doesn't understand `file://`
Did you get that using the Add parts button? Or maybe pasting the path from another place?

**Comment by matthieu-lapeyre** [comment]
Indeed, it works with the add_part bouton. It will do the job. 

Thanks !
